# ===================================================================
# Conda Base Configuration (conda.yaml)
# ===================================================================
# Defines the environment name, channels, and core base packages (Python, PyTorch, CUDA).
# To create and activate the environment, run the following commands:
# conda env create -f conda.yaml
# conda activate SRUM
# ===================================================================

name: SRUM
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults

dependencies:
  - python=3.10
  - pip
  - pytorch
  - torchvision
  - pytorch-cuda=12.1
  - flash-attn==2.7.0.post2
